# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 01:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionary',
            name='response',
        ),
        migrations.RemoveField(
            model_name='item',
            name='log',
        ),
        migrations.RemoveField(
            model_name='keyvaluepair',
            name='container',
        ),
        migrations.RemoveField(
            model_name='keyvaluepair',
            name='key',
        ),
        migrations.RemoveField(
            model_name='response',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='response',
            name='log',
        ),
        migrations.RemoveField(
            model_name='response',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dictionary',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='KeyValuePair',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
